Add "Mark as Unread" feature for alerts
MyBBStuff/MyAlerts pull request #316
Opened 2023-11-26 17:03 UTC by Eldenroot

DRAFT

2023-11-26 19:17 UTC, Eldenroot commented
Fixes #223

2023-12-04 11:48 UTC, lairdshaw requested changes

2023-12-04 22:05 UTC, Eldenroot commented on jscripts/myalerts.js
> +            bodySelector.on("click", ".markUnreadAlertButton", markReadAlertProxy);
Typo, thank you, fixed!

2023-12-04 22:07 UTC, Eldenroot commented on jscripts/myalerts.js
> +                alertId = button.attr("id").substring(15);
Fixed, thx!

2024-03-05 17:03 UTC, closed without merging