Fixes #319 - shrinked content in alert page/modal window
MyBBStuff/MyAlerts pull request #320
Opened 2023-11-26 19:07 UTC by Eldenroot

Add width tag and add align missing tag

2023-12-09 09:50 UTC, Eldenroot commented
Width is not added for these templates, so if the thread has a long title -> it shrinks the column for date/time. Please try it on your own. Also I added "center" for date/time alignment. Anyway I can update the PR and delete the width change.

2024-02-15 10:11 UTC, lairdshaw commented
> Please try it on your own.

I've just done that. I can't reproduce a shrunken date/time column. When the thread title is overlong, the popup stretches to fit, although the close button "X" doesn't shift along with it. I think we can live with that minor glitch. See the image below for what I'm seeing.

![Screenshot 2024-02-15 at 19-57-02 Recent Alerts - Forums (1)](https://github.com/MyBBStuff/MyAlerts/assets/3241722/8a395387-f638-4663-9637-eb9695e624ad)

Maybe you have added custom styling somewhere like a `max-width` which is causing this problem on your own board? Or maybe I've forgotten about something I've done on my vanilla dev board which is fixing the problem.

2024-03-05 17:03 UTC, Eldenroot commented
It is weird... maybe because of Czech language MyBB core pack?

2024-03-07 03:11 UTC, lairdshaw commented
Oh, wait, I see that with a longer date ("Less than 1 minute ago")  it actually does appear shrunken. Is this the sort of thing you mean?

![Screenshot 2024-03-07 at 13-09-47 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234](https://github.com/MyBBStuff/MyAlerts/assets/3241722/966c30f6-8e00-4075-9d96-09b0df7a2eab)

2024-03-07 05:12 UTC, Eldenroot commented
Yes

2024-03-07 05:50 UTC, lairdshaw commented
Hmm. It seems that that's an extreme scenario, with no breaking whitespace in the thread's subject. When I insert regular whitespace characters, it seems fine:

![Screenshot 2024-03-07 at 15-47-30 Recent Alerts - Forums (1)](https://github.com/MyBBStuff/MyAlerts/assets/3241722/69c51de2-178c-4827-8ee7-dc00e6d1b504)

And when I remove a few "words" from the title, it also looks fine:

![Screenshot 2024-03-07 at 15-46-49 Recent Alerts - Forums (1)](https://github.com/MyBBStuff/MyAlerts/assets/3241722/eecbef9c-2400-4ec7-a0cb-ec020edbc441)

Do you have any examples other than extreme scenarios like that of my previous post that you can share?

2024-03-07 09:55 UTC, Eldenroot commented
Almost any longer thread name

2024-03-08 04:22 UTC, lairdshaw commented
Screenshot?

2024-03-12 10:59 UTC, lairdshaw commented
@Eldenroot, sorry, but I don't think that the issue this PR solves is really an issue (aside from the alignment fix). I think browsers do a satisfactory job of managing column widths without explicit width styling, and I also think that when an explicit width is provided, oftentimes it is unnecessarily long and thus over-truncates the *alert description* column, causing another problem of the type it was designed to fix.

To ease your disappointment, please note that PR #323 increases the overall width of the modal popup to make room for the new "Unread only" checkbox.

I'd be happy to merge this PR if you remove the width styling and simply keep the alignment styling.

Alternatively, maybe @euantorano disagrees with me and agrees with you, in which case, the PR can be merged as-is.

2024-03-24 00:00 UTC, Eldenroot commented
@lairdshaw - reverted changes, please merge

2024-03-24 23:22 UTC, lairdshaw requested changes

2024-03-24 23:22 UTC, lairdshaw commented on inc/plugins/MybbStuff/MyAlerts/templates/alert_row.html
> +    <td class="{$altbg} alert__avatar" width="50px" align="center">
As best I can tell, the `width` attribute takes only a number or a number followed by a percentage sign, not a number followed by "px". I might be wrong about this, but if I'm not, this change should be reverted before we merge the PR.

2024-03-27 05:49 UTC, merged

2024-03-27 05:54 UTC, Eldenroot commented
Yes, you are righz. I missed this.

2024-03-27 05:57 UTC, lairdshaw commented
Not to worry; I made the change for you.